---
- name: Create docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ ansible_env.HOME }}/docker-compose.yml"
    mode: '0644'

- name: Create nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ ansible_env.HOME }}/nginx.conf"
    mode: '0644'

- name: Create .env
  ansible.builtin.copy:
    src: .env
    dest: "{{ ansible_env.HOME }}/.env"
    mode: '0600'

- name: Ensure certs directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/certs"
    state: directory
    mode: '0755'

- name: Generate an OpenSSL private key
  community.crypto.openssl_privatekey:
    path: "{{ ansible_env.HOME }}/certs/nginx.key"
    size: 2048
    mode: '0600'

- name: Generate a CSR
  community.crypto.openssl_csr:
    path: "{{ ansible_env.HOME }}/certs/nginx.csr"
    privatekey_path: "{{ ansible_env.HOME }}/certs/nginx.key"
    common_name: "{{ DOMAIN_NAME }}"

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: "{{ ansible_env.HOME }}/certs/nginx.crt"
    privatekey_path: "{{ ansible_env.HOME }}/certs/nginx.key"
    csr_path: "{{ ansible_env.HOME }}/certs/nginx.csr"
    provider: selfsigned
    selfsigned_not_after: "+365d"

- name: Start docker-compose services
  ansible.builtin.command: docker-compose up -d --force-recreate
  args:
    chdir: "{{ ansible_env.HOME }}"

- name: Wait for MariaDB to be ready
  community.docker.docker_container_exec:
    container: mariadb
    command: mysqladmin ping --silent
  register: mariadb_ping
  until: mariadb_ping.rc == 0
  retries: 24
  delay: 5

- name: Download WP-CLI in WordPress container
  community.docker.docker_container_exec:
    container: wordpress
    command: curl -o /tmp/wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

- name: Make WP-CLI executable
  community.docker.docker_container_exec:
    container: wordpress
    command: chmod +x /tmp/wp-cli.phar

- name: Move WP-CLI to bin
  community.docker.docker_container_exec:
    container: wordpress
    command: mv /tmp/wp-cli.phar /usr/local/bin/wp

- name: Configure WordPress (wp-config.php)
  community.docker.docker_container_exec:
    container: wordpress
    command: >
      sh -c 'cd /var/www/html && wp config create
      --dbname=$MYSQL_DATABASE
      --dbuser=$MYSQL_USER
      --dbpass=$MYSQL_PASSWORD
      --dbhost=$MYSQL_HOST
      --allow-root'

- name: Install WordPress
  community.docker.docker_container_exec:
    container: wordpress
    command: >
      sh -c 'cd /var/www/html && wp core install
      --url=$DOMAIN_NAME
      --title="Mon Super Blog"
      --admin_user=$WP_ADMIN_USER
      --admin_password=$WP_ADMIN_PASSWORD
      --admin_email=$WP_ADMIN_EMAIL
      --allow-root'
